apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4-dep-health-check
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-health
  template:
    metadata:
      labels:
        app: service-health
    spec:
      containers:
        - name: ct-service4-health-check
          image: python:3.8
          imagePullPolicy: IfNotPresent
          command: ['/bin/bash','-c','echo $(hostname) > index.html && sleep 60 && python -m http.server 8080']
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 35
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20