apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: pod5-liveness-http
spec:
  containers:
    - name: liveness
      image: registry.hub.docker.com/davidliyutong/liveness:latest
      imagePullPolicy: IfNotPresent
      command: ['/server']
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
          httpHeaders:
            - name: X-Custom-Header
              value: Awesome
        initialDelaySeconds: 3
        periodSeconds: 3
