apiVersion: v1
kind: Pod
metadata:
  name: pod6-liveness-tcp
  labels:
    app: liveness-tcp
spec:
  containers:
    - name: ct-liveness-tcp
      image: python:3.8
      imagePullPolicy: IfNotPresent
      command: ["bash", "-c", "echo test > index.html && sleep 30 && python -m http.server 8080"]
      ports:
        - containerPort: 8080
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 35
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20