apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  cephfs:
    monitors:
      - 10.125.224.26:6789
    path: /xxx
    user: admin
    secretRef:
      name: ceph-luminous-admin
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle