# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/zesty64"
    master.vm.network :private_network, ip: "88.88.88.2"
    #master.vm.network :public_network
    master.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--cpus", "3"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end
    master.vm.provision "shell", inline: "sh /vagrant/install_kubeadm.sh master"
  end

#  config.vm.define "node1" do |node1|
#    node1.vm.box = "ubuntu/zesty64"
#    node1.vm.network :private_network, ip: "88.88.88.3"
#    #node1.vm.network :public_network
#    node1.vm.provider :virtualbox do |vb|
#        vb.customize ["modifyvm", :id, "--memory", "4096"]
#        vb.customize ["modifyvm", :id, "--cpus", "3"]
#        vb.customize ["modifyvm", :id, "--ioapic", "on"]
#    end
#    node1.vm.provision "shell", inline: "sh /vagrant/install_kubeadm.sh node1"
#  end

#  config.vm.define "node2" do |node2|
#    node2.vm.box = "ubuntu/zesty64"
#    node2.vm.network :private_network, ip: "88.88.88.4"
#    #node2.vm.network :public_network
#    node2.vm.provider :virtualbox do |vb|
#        vb.customize ["modifyvm", :id, "--memory", "4096"]
#        vb.customize ["modifyvm", :id, "--cpus", "3"]
#        vb.customize ["modifyvm", :id, "--ioapic", "on"]
#    end
#    node2.vm.provision "shell", inline: "sh /vagrant/install_kubeadm.sh node2s"
#  end

    config.vm.boot_timeout=500
end
