apiVersion: v1
kind: Pod
metadata:
  name: secret3-pod-volume
spec:
  containers:
    - name: ct-busybox
      image: radial/busyboxplus
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "ls /xxx && sleep 1000000"]
      volumeMounts:
        - name: secret2-vol
          mountPath: "/xxx"
          readOnly: true
  volumes:
    - name: secret2-vol
      secret:
        secretName: secret2
